DROP TABLE IF EXISTS ingredients;

CREATE TABLE ingredients(
    id SERIAL PRIMARY KEY,
    title VARCHAR NOT NULL,
    severity INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ingredients (title) VALUES 
    ('agave syrup'),
    ('agavendicksaft'),
    ('amarinth flour'),
    ('amarinthmehl'),
    ('bareley'),
    ('bloß'),
    ('buttermilk'),
    ('buttermilch'),
    ('chicken salt'),
    ('hühnersalz'),
    ('chicory root'),
    ('zichorienwurzel'),
    ('zichorienwurzel extrakt'),
    ('chicory root extract'),
    ('chickpea flour'),
    ('kichererbsenmehl'),
    ('besan'),
    ('coconut flour'),
    ('kokosnussmehl'),
    ('einkorn'),
    ('emmer'),
    ('erythritol'),
    ('erythritöl'),
    ('e968'),
    ('fructans'),
    ('fruktane'),
    ('fruchtzucker'),
    ('obstzucker'),
    ('fructooligosaccharides'),
    ('fructooligosaccharide'),
    ('fos'),
    ('fructose'),
    ('fruit concentrate'),
    ('fruchtkonzentrat'),
    ('obstkonzentrat'),
    ('fruit juice'),
    ('fruchtsaft'),
    ('obstsaft'),
    ('garlic'),
    ('knoblauch'),
    ('knoblauchpulver'),
    ('knoblauchpuder'),
    ('garlic powder'),
    ('garlic salt'),
    ('knoblauchsalz'),
    ('glucose fructose syrup'),
    ('glukose fructosesirup'),
    ('gram flour'),
    ('gramm mehl'),
    ('honey'),
    ('honig'),
    ('high fructose corn syrup'),
    ('maissirup mit hohem fruktosegehalt'),
    ('hfcs'),
    ('inulin'),
    ('isoglucose'),
    ('isoglukose'),
    ('isolated fructose'),
    ('isolierte fruktose'),
    ('isomalt'),
    ('e953'),
    ('khorasan flour'),
    ('kamut'),
    ('lactose'),
    ('laktose'),
    ('milchzucker'),
    ('lentil flour'),
    ('linsenmehl'),
    ('lupin'),
    ('maltitol'),
    ('e956'),
    ('mannitol'),
    ('e421'),
    ('milk'),
    ('milch'),
    ('milk curds'),
    ('milchquark'),
    ('milch quark'),
    ('onion'),
    ('zwiebel'),
    ('onion salt'),
    ('zwiebel salz'),
    ('onion powder'),
    ('zwiebelpulver'),
    ('zwiebel pulver'),
    ('sorbitol'),
    ('sorbitöl'),
    ('e420'),
    ('sour cream'),
    ('sauerrahm'),
    ('saure sahne'),
    ('schmand'),
    ('xylitol'),
    ('e967'),
    ('yogurt'),
    ('joghurt'),
    ('Jogurt'),
    ('yoghurt')

    
;